version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: app.dockerfile
    ports:
      - '80:3000'
    environment:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    command: >
      sh -c "npm run build && npm start"
