services:
  nextjs:
    build:
      context: .
      dockerfile: app.dockerfile
    container_name: nextjs
    expose:
      - '3000'
    ports:
      - '3000:3000'
    environment:
      - .env
    restart: always
    networks:
      - app-network
    volumes:
      - .:/app
      - /app/node_modules
    command: >
      sh -c 'npm run build && npm start'

  nginx:
    image: nginx:stable
    container_name: nginx-proxy
    ports:
      - '80:80'
      - '443:443'
    depends_on:
      - nextjs
    restart: always

    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl:/etc/nginx/ssl

    networks:
      - app-network

networks:
  app-network:
    driver: bridge

